name: Generate Documentation

on: 
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'  # 根据你的项目实际情况选择版本

      - name: Install DocFX
        run: |
          wget https://github.com/dotnet/docfx/releases/download/v2.56.7/docfx.zip
          unzip docfx.zip -d docfx

      - name: Generate Docs
        run: |
          ./docfx/docfx.exe build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Push to gh-pages branch
          FOLDER: _site  # DocFX default location
          CLEAN: true  # Clean up old files
