name: Generate Documentation

on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.7.2'  # Use .NET Framework 4.7.2

      - name: Install DocFX
        run: |
          Invoke-WebRequest -Uri "https://github.com/dotnet/docfx/releases/download/v2.56.7/docfx.zip" -OutFile "docfx.zip"
          Expand-Archive -Path "docfx.zip" -DestinationPath "docfx"

      - name: Generate Docs
        run: |
          ./docfx/docfx.exe build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Deploy to gh-pages branch
          FOLDER: _site  # Default output folder for DocFX
          CLEAN: true  # Clean out old files
